### ISSUE TITLE
"copy" script is backwards

### ISSUE THREAD

**Issue by tremby** [rbartoli/react-boilerplate#4]
Unless I'm mistaken, the `copy` script in the package.json is backwards. It's copying everything in `public` to the `build` directory. Shouldn't that be the other way around?

**Comment by rbartoli** [comment]
Hi @tremby,

Because the `public` folder contains version controlled files and the `build` directory contains files that are generated at build time (but not version controlled), the `copy` script is correct.

The `build` folder is the "deployable" one, while the `public` folder contains static assets that are meant to be deployed.

Hope this makes sense.

Thanks

**Comment by tremby** [comment]
Then shouldn't the dev server's base be `build` rather than `public` in the webpack configuration?

**Comment by rbartoli** [comment]
No, it shouldn't. `webpack-dev-server` keeps everything in memory and it doesn't write to the filesystem, so it's only sourcing the assets from the `public` directory.

The `build` directory doesn't exist when in dev mode. Try checking the project's root directory after running `npm start` and you'll see that the directory is not there.

**Comment by tremby** [comment]
OK, I understand. Thanks.

**Comment by rbartoli** [comment]
No problem, I hope that everything does make sense.
